### ISSUE TITLE
3.2.3 milestones

### ISSUE THREAD

**Issue by laliberte** [pydap/pydap#122]
I propose a 3.2.3 version release soon-ish, focused on bug fixes:

- [ ] Make localtestserver more usable by remove serverside functions #119 
- [ ] Expand the build matrix to include dependency testing for different user types #120 
- [ ] Other bug fixes (e.g. #121)

**Comment by Juanlu001** [comment]
What about 3.3.0, now that Python 3.4 support has been dropped?

**Comment by captainkirk99** [comment]
See discussion in #240.

**Comment by captainkirk99** [comment]
These have all been done, and released in 3.3.0. I will close this issue.
